# Generated by Django 2.0.8 on 2018-10-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_link',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
